/*
 * A debug(...) macro for C.
 *
 * Created: Aug 11, 2020. leiless.
 * License: MIT
 * Repo:    https://github.com/leiless/dbg.h
 */

/* UUID generated by: https://www.uuidgenerator.net/ */
#ifndef DBG_H_c49aa87c_54eb_46d2_8d72_a51f5efce1ac
#define DBG_H_c49aa87c_54eb_46d2_8d72_a51f5efce1ac



#endif
